// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/24/2024, 8:27:07 PM
const configMerger = require("/Users/marquis.abah/ChineduEcommerce/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/marquis.abah/ChineduEcommerce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/plugins/**/*.{js,ts,mjs}","/Users/marquis.abah/ChineduEcommerce/composables/**/*.{js,ts,mjs}","/Users/marquis.abah/ChineduEcommerce/utils/**/*.{js,ts,mjs}","/Users/marquis.abah/ChineduEcommerce/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis.abah/ChineduEcommerce/app.config.{js,ts,mjs}"] }));

module.exports = config
